//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmestajDanTrebit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmestajDanTrebit.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancient Theatre Ohrid.
        /// </summary>
        public static string Anticki {
            get {
                return ResourceManager.GetString("Anticki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find accomodation in Ohrid.
        /// </summary>
        public static string Find_accomodation_in_Ohrid {
            get {
                return ResourceManager.GetString("Find accomodation in Ohrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Accomodation.
        /// </summary>
        public static string FindAccomodation {
            get {
                return ResourceManager.GetString("FindAccomodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here, you can find information on different hotels and apartments you can book for your stay in Ohrid.
        /// </summary>
        public static string Intro1 {
            get {
                return ResourceManager.GetString("Intro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also, see the places recommended by us that you should visit on your trip here.
        /// </summary>
        public static string Intro2 {
            get {
                return ResourceManager.GetString("Intro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy your stay in this beautiful city!.
        /// </summary>
        public static string Intro3 {
            get {
                return ResourceManager.GetString("Intro3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Church Sv. Jovan Kaneo.
        /// </summary>
        public static string Kaneo {
            get {
                return ResourceManager.GetString("Kaneo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places to visit.
        /// </summary>
        public static string PlacesToVisit {
            get {
                return ResourceManager.GetString("PlacesToVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Info.
        /// </summary>
        public static string ShowInfo {
            get {
                return ResourceManager.GetString("ShowInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monastery Sv. Naum of Ohrid.
        /// </summary>
        public static string Sv_Naum {
            get {
                return ResourceManager.GetString("Sv Naum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to our page!.
        /// </summary>
        public static string Welcome_to_our_page {
            get {
                return ResourceManager.GetString("Welcome to our page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Museum &quot;Bay of Bones&quot;.
        /// </summary>
        public static string Zaliv {
            get {
                return ResourceManager.GetString("Zaliv", resourceCulture);
            }
        }
    }
}
